name       : python-typing-extensions
version    : 3.7.4.3
release    : 2
source     :
    - https://files.pythonhosted.org/packages/16/06/0f7367eafb692f73158e5c5cbca1aec798cdf78be5167f6415dd4205fa32/typing_extensions-3.7.4.3.tar.gz : 99d4073b617d30288f569d3f13d2bd7548c3a7e4c8de87db09a9d29bb3a4a60c
homepage   : https://pypi.org/project/typing-extensions/
license    : Python-2.0
component  : programming.python
summary    : Typing Extensions – Backported and Experimental Type Hints for Python
description: |
    The "typing" module was added to the standard library in Python 3.5 on a provisional basis and will no longer be provisional in Python 3.7. However, this means users of Python 3.5 - 3.6 who are unable to upgrade will not be able to take advantage of new types added to the "typing" module, such as "typing.Text" or "typing.Coroutine".
builddeps  :
    - python-tox
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test tox3 -e py37
