name       : python-typing-extensions
version    : 3.7.4.1
release    : 1
source     :
    - https://files.pythonhosted.org/packages/e7/dd/f1713bc6638cc3a6a23735eff6ee09393b44b96176d3296693ada272a80b/typing_extensions-3.7.4.1.tar.gz : 091ecc894d5e908ac75209f10d5b4f118fbdb2eb1ede6a63544054bb1edb41f2
license    : Python-2.0
component  : programming.python
summary    : Typing Extensions – Backported and Experimental Type Hints for Python
description: |
    The "typing" module was added to the standard library in Python 3.5 on a provisional basis and will no longer be provisional in Python 3.7. However, this means users of Python 3.5 - 3.6 who are unable to upgrade will not be able to take advantage of new types added to the "typing" module, such as "typing.Text" or "typing.Coroutine".
build      : |
    %python3_setup
install    : |
    %python3_install
