name       : python-typing-extensions
version    : 3.10.0.2
release    : 5
source     :
    - https://pypi.io/packages/source/t/typing-extensions/typing_extensions-3.10.0.2.tar.gz : 49f75d16ff11f1cd258e1b988ccff82a3ca5570217d7ad8c5f48205dd99a677e
homepage   : https://pypi.org/project/typing-extensions/
license    : Python-2.0
component  : programming.python
summary    : Typing Extensions – Backported and Experimental Type Hints for Python
description: |
    The "typing" module was added to the standard library in Python 3.5 on a provisional basis and will no longer be provisional in Python 3.7. However, this means users of Python 3.5 - 3.6 who are unable to upgrade will not be able to take advantage of new types added to the "typing" module, such as "typing.Text" or "typing.Coroutine".
builddeps  :
    - python-tox
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test tox -e py39
