name       : python-typing-extensions
version    : 4.4.0
release    : 7
source     :
    - https://pypi.io/packages/source/t/typing-extensions/typing_extensions-4.4.0.tar.gz : 1511434bb92bf8dd198c12b1cc812e800d4181cfcb867674e0f8279cc93087aa
homepage   : https://github.com/python/typing_extensions
license    : Python-2.0
component  : programming.python
summary    : Typing Extensions – Backported and Experimental Type Hints for Python
description: |
    The "typing" module was added to the standard library in Python 3.5 on a provisional basis and will no longer be provisional in Python 3.7. However, this means users of Python 3.5 - 3.6 who are unable to upgrade will not be able to take advantage of new types added to the "typing" module, such as "typing.Text" or "typing.Coroutine".
builddeps  :
    - python-build
    - python-flit-core
    - python-installer
    - python-packaging
build      : |
    %python3_setup
install    : |
    %python3_install
