name       : python-typing-extensions
version    : 4.3.0
release    : 6
source     :
    - https://pypi.io/packages/source/t/typing-extensions/typing_extensions-4.3.0.tar.gz : e6d2677a32f47fc7eb2795db1dd15c1f34eff616bcaf2cfb5e997f854fa1c4a6
homepage   : https://github.com/python/typing_extensions
license    : Python-2.0
component  : programming.python
summary    : Typing Extensions – Backported and Experimental Type Hints for Python
description: |
    The "typing" module was added to the standard library in Python 3.5 on a provisional basis and will no longer be provisional in Python 3.7. However, this means users of Python 3.5 - 3.6 who are unable to upgrade will not be able to take advantage of new types added to the "typing" module, such as "typing.Text" or "typing.Coroutine".
builddeps  :
    - python-build
    - python-flit-core
    - python-installer
    - python-packaging
build      : |
    %python3_setup
install    : |
    %python3_install
